#!/bin/sh

echo "*****Running gradle build******"
RED='\033[0;31m'
./gradlew spotlessCheck
spotless_result=$?
if [ "$spotless_result" -eq 1 ]
then
  ./gradlew spotlessApply
  echo "\n\n\n${RED}BUILD FAILED due to SpotlessCheck! \nThere are some spotless code format fix. Please review and add them to git."
  exit 1
fi

./gradlew checkstyleMain
checkstyle_result=$?
if [ "$checkstyle_result" -eq 1 ]
then
  echo "\n\n\n${RED}BUILD FAILED due to Checkstyle! \nPlease fix the checkstyle issues and try again."
  exit 1
fi

./gradlew build
build_result=$?

# return 1 exit code if running checks fails
if [ "$build_result" -eq 1 ]
then
  echo "\n\n\n${RED}BUILD FAILED!\nThere is a build failure. Please fix the build issues and try again."
  exit 1
else
  exit 0
fi
